# when using the bot, make sure to rename this to just "config.toml"

MAIN_TOKEN = "TOKEN"  # your discord bot token, of course!

DEV_GUILD_ID = 11111111111111111  # guild id that you own and that will not be used for a playerlist
BOT_COLOR = 11557887  # a color to color some embeds and all - it's nice for branding.
SETUP_LINK = "https://rpl.astrea.cc/wiki/server_setup.html"  # a link to how to set up the bot for a server
PREMIUM_INFO_LINK = "https://rpl.astrea.cc/wiki/premium.html"  # a link about premium

DOCKER_MODE = false  # whether or not the bot is running in docker. if it is, it'll automatically use the docker redis and postgres, and you can leave the next two entries blank
DB_URL = "POSTGRESDB_URL"  # a url to a postgres database
REDIS_URL = "REDIS_URL"  # url to a redis database

# worth noting for docker:
# - you'll need a .env file with a POSTGRES_PASSWORD entry (POSTGRES_PASSWORD="PASSWORD"). docker limitation, i would squeeze it in config.toml if i could

# - docker compose run --env DB_URL="postgresql://postgres:YOUR_DB_PASSWORD@db:5432/postgres" bot python -m prisma migrate dev (or deploy in a prod environment and care about non-destructive changes)
# or you can use the shell directly in the container and run the commands from there: docker compose run --env DB_URL="postgresql://postgres:YOUR_DB_PASSWORD@db:5432/postgres" bot bash
# you'll need to run one of those commands to initialize the database on your first run, but it shouldn't be needed after that
# also, see https://www.prisma.io/docs/concepts/components/prisma-migrate

# - you can swap out the redis for any redis supporting backend, though i'd suggest keeping the name of the entry in the compose file "redis" because
# the bot relies on that to connect to it

SENTRY_DSN = "SENTRY_DSN" # the dsn for sentry. optional, you can leave it blank if you don't want to use it

# these next two are generated by the beginning instructions here:
# https://github.com/Astrea-Stellarium-Labs/elytra-ms#make-an-application
XBOX_CLIENT_ID = "ID"
XBOX_CLIENT_SECRET = "SECRET"

# you'll also need a token file called "tokens.json" in the root directory of the bot, generated by
# https://github.com/Astrea-Stellarium-Labs/elytra-ms#make-an-application
# the name is currently hardcoded, but i'll make it configurable in the future

OPENXBL_KEY = "KEY"  # register an account at https://xbl.io/ and you'll get a token to use

# bot list site tokens. leave blank or remove the entries if you don't want to use them
TOP_GG_TOKEN = ""
DBL_TOKEN = ""

# various emojis used throughout the bot. more or less self explanatory
GREEN_CIRCLE_EMOJI="RAW EMOJI STRING"
GRAY_CIRCLE_EMOJI="RAW EMOJI STRING"
WINDOWS_EMOJI_ID="EMOJI ID"
SWITCH_EMOJI_ID="EMOJI ID"
IOS_EMOJI_ID="EMOJI ID"
ANDROID_EMOJI_ID="EMOJI ID"
XBOX_ONE_EMOJI_ID="EMOJI ID"
XBOX_SERIES_EMOJI_ID="EMOJI ID"
PLAYSTATION_EMOJI_ID="EMOJI ID"
UNKNOWN_DEVICE_EMOJI_ID="EMOJI ID"

# the key used to encrypt premium codes. make this a very strong and random 64 character code
PREMIUM_ENCRYPTION_KEY = "KEY"